# server
server:
  port: 8099

# swagger	
swagger2:
  title: API
  description: description
  version: v0.0.1
  basePackage: com.zhuphon
  author: Zhu Phon
  url: localhost
  
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boot
    username: root
    password: ''
    
mybatis:
  mapper-locations: classpath*:/mappers/*Mapper.xml